/// gml_Object_pu1_Create_0
action_set_relative(0);
distrutti = 0;
over = 0;
shifta = 0;
menoo = 0;
action_set_relative(1);
action_create_object(pu7, 92, 0);
action_set_relative(0);
action_set_relative(1);
action_create_object(handbutton, 92, 0);
action_set_relative(0);
action_set_relative(1);
action_create_object(buildbutton, 92, 0);
action_set_relative(0);
action_set_relative(1);
action_create_object(eyebutton, 92, 0);
action_set_relative(0);
action_set_relative(1);
action_create_object(backobutton, 92, 0);
action_set_relative(0);
action_set_relative(1);
action_create_object(eyebutton1, 92, 0);
action_set_relative(0);
action_set_relative(1);
action_create_object(eyebutton2, 92, 0);
action_set_relative(0);
action_set_relative(1);
action_create_object(eyebutton3, 92, 0);
action_set_relative(0);
action_set_relative(1);
action_create_object(zoom_plus, 92, 0);
action_set_relative(0);
action_set_relative(1);
action_create_object(zoom_minus, 92, 0);
action_set_relative(0);
action_set_relative(1);
action_create_object(pu2, 184, 0);
action_set_relative(0);
action_set_relative(1);
action_create_object(pu3, 302, 0);
action_set_relative(0);
action_set_relative(1);
action_create_object(pu6, 410, 0);
action_set_relative(0);
action_set_relative(1);
action_create_object(pu4prov, 492, 0);
action_set_relative(0);
action_set_relative(1);
action_create_object(pu5prov, 591, 0);
action_set_relative(0);
action_set_relative(1);
action_create_object(pudj, 591, 0);
action_set_relative(0);
action_set_relative(1);
action_create_object(pusolare, 591, 0);
action_set_relative(0);
action_set_relative(1);
action_create_object(pugatling, 591, 0);
action_set_relative(0);
action_set_relative(1);
action_create_object(puvillone, 591, 0);
action_set_relative(0);
action_set_relative(1);
action_create_object(pumediat, 591, 0);
action_set_relative(0);
action_set_relative(1);
action_create_object(puruspa, 742, 0);
action_set_relative(0);
action_set_relative(1);
action_create_object(pureset, 742, 0);
action_set_relative(0);
action_set_relative(0);
